### PR TITLE
[Software][cli11] Add submodules cli11

### PR DESCRIPTION
**Pull request by jmmourier**
this module will help parse argument for applications

### CODE REVIEW

**Comment by capozzid** [comment]
I've added as well a new submodule (grpc) but in a new folder "external" located in ./software/modules/external so we keep all external libraries in a separated folder that should be gitignored

**Comment by jmmourier** [comment]
Do we need the external subfolder ? using git submodule add isn't enough ?

**Comment by capozzid** [comment]
> Do we need the external subfolder ? using git submodule add isn't enough ?

Unfortunately we do because git will install the sources of the added lib from .gitmodule in the targetet folder. That's why we need one "external" folder that will be part of .gitignore. You can see an example in this commit https://github.com/jmmourier/laughing-couscous/pull/14/commits/bffa369142a2ffaf1e0699be71ad2ed2f580c83d

**Comment by jmmourier** [comment]
@capozzid ok for me to put it in externql folder, I will to it this evening

**Comment by jmmourier** [comment]
@capozzid I close the PR I will wait for the merge of grpc to avoid unnecessary conflicts

**Pull request closed without merging**
