### PR TITLE
[Soft][missi] add json lib and implement mission from file

### PR DESCRIPTION
**Pull request by jmmourier**
This implement the mission from json file. 
this include using a Json lib, reading the mission from a file and providing the next action to perform as an object "Action".

### CODE REVIEW

**Comment by capozzid** [comment]
hum... I'll check that tomorrow but I can already tell you that your code isn't formatted 😄

**Review by devkgs — APPROVED** [review]

**Review by capozzid — CHANGES_REQUESTED** [review]
code format

**Comment by jmmourier** [comment]
> code format

On the principe I agree that it's nicer, but the purpose is to ease the review. 
Are you telling me the PR is hard to review because the format ?

**Comment by capozzid** [comment]
formating code should be automatic. It is very easy to do it and it allows us to have the exact same format for the same language

**Comment by jmmourier** [comment]
> formating code should be automatic. It is very easy to do it and it allows us to have the exact same format for the same language

This can be discussed, we can all have our own preference to formatting code. 
But this is not productive discussion here, we want the robot to works :) 
code formatted as requested sir

**Review by capozzid — APPROVED** [review]

**Pull request merged**
